config/routes.rb
Rails.application.routes.draw do
  resources :users

  root 'events#index'

  resources :events

end

app/models/event.rb
class Event < ActiveRecord::Base
  validates :name, presence: true
  validates :time, presence: true
  validates :place, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :email, presence: true
  validates_uniqueness_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  
  def index
    @events = Event.all
  end
  
  def new
    @event = Event.new
  end
  
  def show
    @event = Event.find(params[:id])
  end
  
  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to event_path(@event)
    else
      render 'new'
    end
  end
  
  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    flash[:notice] = '#{@event.name} has been removed or canceled'
    redirect_to root_path
  end
  
  def edit
    @event = Event.find(params[:id])
  end
    
  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      redirect_to event_path(@event)
    else  
      render 'edit'
    end
  end
  
  private
  def event_params
    params.require(:event).permit(:name, :time, :place)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      redirect root_url, notice: "Thanks for signing up!"
    else
      render "new"
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= render('layouts/errors') %>

<%= form_for(@event) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br>
  <p>2015-09-05 07:02"</p>
  <%= f.label :time %>
  <%= f.text_field :time %><br>
  <%= f.label :place %>
  <%= f.text_field :place %>
  <%= f.submit %>
<% end %> 

app/views/events/edit.html.erb
<h1>Edit <%= @event.name %> Event</h1>

<%= render('form') %>    

app/views/events/index.html.erb
<h1>Events</h1>
<ul>
  <% @events.each do |event| %>
  <li><%= link_to "#{event.name}", event_path(event.id) %></li>
  <% end %>
</ul>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render('form') %>    

app/views/events/show.html.erb
<h1><%= @event.name %></h1>


<h3><%= @event.name %></h3>
<h3><%= @event.time %></h3>
<h3><%= @event.place %></h3>

<%= link_to "Edit", edit_event_path(@event) %>
<%= link_to "Delete", event_path(@event), :data => {:confirm => "You sure?", :method => "delete"} %>

app/views/layouts/_errors.html.erb
<% if @event.errors.any? %>
<h4>We Have a Problem...</h4>
  <ul>
    <% @event.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_errors_event.html.erb
<% if @event.errors.any? %>
<h4>We Have a Problem...</h4>
  <ul>
    <% @event.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_errors_user.html.erb
<% if @user.errors.any? %>
<h4>We Have a Problem...</h4>
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Events</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <div class="row">
    <div class="nav-bar">
      <ul class="button-group">
        <li><%= link_to "Home", root_path %>/</li>
        <li><%= link_to "New", new_event_path %></li>
        <li><%= link_to "Sign Up", new_user_path %></li>
      </ul>
    </div>
  
  <%= yield %>
</div>
</body>
</html>

app/views/users/_form.html.erb
<%= render('layouts/errors_user') %>

<%= form_for(@user) do |f| %>
  <%= f.label :email %>
  <%= f.text_field :email %><br>
  <%= f.label :password %>
  <%= f.text_field :password %><br>
  <%= f.label :password_confirmation %>
  <%= f.text_field :password_confirmation %>
  <%= f.submit %>
<% end %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render('form') %>